### ISSUE TITLE
如何绑定域名访问呢

### ISSUE THREAD

**Issue by murongqingsi** [tmoonlight/NSmartProxy#10]
服务端我假设在了  A 服务器上，内网服务器B 上面有个网站要外网访问。我设置了B:81指向了A:80的节点配置。那我的域名 test.test.com 应该在dns 解析里面只想哪儿，在浏览器怎么访问呢。

**Comment by weinre** [comment]
> 要外网
windows 服务器 用iis转发  centos 用nginx转发
域名解析到外网服务器A

**Comment by murongqingsi** [comment]
能不能实现多个域名配置访问内网B多个网站，但是A 的端口只用一个呢？

**Comment by weinre** [comment]
> 能不能实现多个域名配置访问内网B多个网站，但是A 的端口只用一个呢？
可以：
windows服务器 用iis转发 centos 用nginx转发

**Comment by tmoonlight** [comment]
NSP目前没有专门针对http做绑定支持，理论上是可以做到的。
目前有两个方案可供选择：
1.假80端口：申请一个可以支持**隐式转发**的域名，看似80端口，实际是做了一步转发
2.真80端口：申请一个支持泛域名解析的域名，通过编码的方式来区分http绑定的不同的主机头从而实现多域名公用。
目前2方案是比较完美的解决办法，不过个人精力有限还没来得及做专门针对http解析的优化，你也可以提PR帮我完善这块。

**Comment by murongqingsi** [comment]
我使用了一下这个服务，调试正常后，发现内网B不能被内网C,内网D ,根据内网ip访问了，比如远程。我关闭内网穿透服务也不好使。

**Comment by tmoonlight** [comment]
你意思是内网服务被影响了？另外客户端要确认下右下角小图标有没有关闭才行。

**Comment by tmoonlight** [comment]
> 我使用了一下这个服务，调试正常后，发现内网B不能被内网C,内网D ,根据内网ip访问了，比如远程。我关闭内网穿透服务也不好使。

可以加我微信 shao871341描述一下你的详细情况

**Comment by murongqingsi** [comment]
对不起，是我看错了，当时挂了vpn,所以不能访问，不是因为你的工具的事。
