### ISSUE TITLE
说明有点乱，跑不起来，而且最新的包不包含run.cmd

### ISSUE THREAD

**Issue by yuanxiongwei** [tmoonlight/NSmartProxy#12]
说明有点乱，跑不起来，而且最新的包不包含run.cmd。能出小白教程不

**Comment by tmoonlight** [comment]
按说明应该可以很快跑起来啊，另外客户端增加了一个winform版本，可以单独跑

**Comment by yuanxiongwei** [comment]
服务端启动后，客户端winform链接不上。还是不容易上手。

**Comment by tmoonlight** [comment]
> 服务端启动后，客户端winform链接不上。还是不容易上手。

可以加我微信，把日志发我看看shao871341
