### ISSUE TITLE
大神 问个问题

### ISSUE THREAD

**Issue by xiaobaizhangjun** [tmoonlight/NSmartProxy#16]
现在我有N台内网服务器，但是只有一个外网地址通过路由器上网，但是我不想把所有服务器通过路由器映射 我想把一台服务器映射出去做NSmartProxy的服务器，通过它访问内网的其他服务器  我需要把这台服务器的所有端口都映射出去还是只需要映射12308 和19974两个端口

**Comment by tmoonlight** [comment]
你这个情况可能不需要映射12309 19974，但是一定要映射应用端口，
举个例子，如果你的映射规则是
waiwang.com:9999=>192.168.1.104:80
waiwang.com:9998=>192.168.1.105:80
你就需要映射9999 9998这两个端口
