### ISSUE TITLE
疑问 连接一段时间之后无法建立新连接，但是已经建立的连接还保持着

### ISSUE THREAD

**Issue by pjy612** [tmoonlight/NSmartProxy#19]
疑问 连接一段时间之后 无法访问内网客户端
但是已经建立的连接还保持着。

目前场景，内网服务器 对外有多个IP。
所以Client对接上Server后 IP可能会变动，不清楚是不是这个影响。
然后 时间长了就连不上 查看Server日志显示是 
内网隧道断开 外网还在

导致新的请求连不上？
烦请解惑

另外日志中内外网都断开的隧道 意义是？

**Comment by tmoonlight** [comment]
你是不是部署在linux上的？linux要修改keepalive配置

**Comment by pjy612** [comment]
没，是在Win下面。win上面需要修改哪些配置？不知道是客户端连不上服务器还是别的什么。。。感觉客户端连服务器是不是要想法子维持起来。。。
不然如果有波动断了后不好连了。。。
用过另一个
https://github.com/bobowire/Wireboy.Socket.P2PSocket
不过 放了一夜后好像也是类似的情况 到后面就不通了。。。 囧

**Comment by tmoonlight** [comment]
可以加我微信871341，把日志发我看看
