### ISSUE TITLE
http协议如何替换成https协议

### ISSUE THREAD

**Issue by jifeilong9** [tmoonlight/NSmartProxy#2]
![image](https://user-images.githubusercontent.com/24316291/54094983-b2eaa180-43df-11e9-9447-931e5d5e558a.png)
你好，我想在开发微信小程序调试时使用，但是微信只支持https协议如何把这个地址设置成https的

**Comment by tmoonlight** [comment]
程序支持所有基于tcp的协议，包括https。确保你服务端是有合法证书就行。

**Comment by weinre** [comment]
> ![image](https://user-images.githubusercontent.com/24316291/54094983-b2eaa180-43df-11e9-9447-931e5d5e558a.png)
> 你好，我想在开发微信小程序调试时使用，但是微信只支持https协议如何把这个地址设置成https的

你好 请问一下 你的问题（用https访问）解决了吗

**Comment by J973** [comment]
配置ssl加密


 
---原始邮件---
发件人: "wehub"<notifications@github.com>
发送时间: 2019年4月18日(星期四) 下午4:03
收件人: "tmoonlight/NSmartProxy"<NSmartProxy@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [tmoonlight/NSmartProxy] http协议如何替换成https协议 (#2)


 

 你好，我想在开发微信小程序调试时使用，但是微信只支持https协议如何把这个地址设置成https的
  
你好 请问一下 你的问题（用https访问）解决了吗

**Comment by J973** [comment]
配置ssl撒

**Comment by weinre** [comment]
> 配置ssl撒

大佬 来个demo啥 感谢不尽

**Comment by weinre** [comment]
iis不知道怎么配置  通过nginx解决
