### ISSUE TITLE
服务端能支持一下  注册成window服务吗

### ISSUE THREAD

**Issue by xilutian** [tmoonlight/NSmartProxy#23]

**Comment by tmoonlight** [comment]
可以，晚点弄一个

**Comment by tmoonlight** [comment]
弄好了，步骤如下：
1.重新下载一下nspserver1.0的发布版本
2.以管理员身份打开命令行
3.按如下命令操作：
注册windows服务
`dotnet NSmartProxy.ServerHost.dll action:install`
卸载windows服务
`dotnet NSmartProxy.ServerHost.dll action:uninstall`
