### ISSUE TITLE
一个使用过程中的问题

### ISSUE THREAD

**Issue by 756616071** [tmoonlight/NSmartProxy#24]
![image](https://user-images.githubusercontent.com/44856671/63143336-5c356380-c020-11e9-9b46-36e693a7a736.png)
在上面已经更改端口为7002了
但是其实访问的还是 7003,7002并不能访问
![image](https://user-images.githubusercontent.com/44856671/63143355-7f601300-c020-11e9-8870-393552fa1784.png)
~好像这个配置没有生效

**Comment by tmoonlight** [comment]
7002端口可能被其他程序占用了，用netstat -an确认下，另外服务端界面上也可以设置绑定端口

**Comment by 756616071** [comment]
谢谢大佬,已经查看到了是一个其他的应用占用了我的端口, 
还有个问题 ,服务端注册成服务后,服务不能停止,也不能进行其他操作
只能把服务给删除了~

**Comment by tmoonlight** [comment]
没发现你这个情况，先试试这个：跟 action:start 后缀开启服务，
跟 action:stop 后缀暂停服务。

**Comment by 756616071** [comment]
谢谢~大佬
服务暂停不了~ 
对了, 建议你在端口映射中加入一个备注,
比如这个端口是用来做啥~

**Comment by tmoonlight** [comment]
> 谢谢~大佬 服务暂停不了~
> 对了, 建议你在端口映射中加入一个备注,
> 比如这个端口是用来做啥~

多谢反馈，不能停止的问题解决了，可以下新版本试试。另外你说的备注具体是加在哪里？

**Comment by 756616071** [comment]
大佬~服务的状态还是这样的~ 是不是因为系统是  2008 的问题导致的 

![image](https://user-images.githubusercontent.com/44856671/63368740-1cb89f80-c3b1-11e9-8113-864275bf74ad.png)

**Comment by tmoonlight** [comment]
从你的截图上看，你没升级，新版本描述应该v1.0_Beta

**Comment by 756616071** [comment]
额  ~~  看错了 ~~我的失误~~
对了 ,能留下你的联系方式嘛 ~~
github上的留言功能太难用了~ 
大佬不方便的话  
你加我qq嘛  756616071

**Comment by tmoonlight** [comment]
可以加我微信 shao871341

**Comment by 756616071** [comment]
好的 已经发送了 请求~
