### ISSUE TITLE
备注的问题

### ISSUE THREAD

**Issue by 756616071** [tmoonlight/NSmartProxy#25]
> 谢谢~大佬 服务暂停不了~
> 对了, 建议你在端口映射中加入一个备注,
> 比如这个端口是用来做啥~

多谢反馈，不能停止的问题解决了，可以下新版本试试。另外你说的备注具体是加在哪里？

_Originally posted by @tmoonlight in https://github.com/tmoonlight/NSmartProxy/issues/24#issuecomment-522988573_

**Comment by 756616071** [comment]
在客户端的这个位置
![image](https://user-images.githubusercontent.com/44856671/63367169-d1e95880-c3ad-11e9-9365-28f6bf2e7f9f.png)
这样加上后可以标注  比如  7001 是远程端口,如果端口使用的多的情况下就不会分不清 
然后还可以在网页端的条目上对应标注下,这样就很明了的看出来是做什么的了 
![image](https://user-images.githubusercontent.com/44856671/63367284-0e1cb900-c3ae-11e9-84d6-462106c32aad.png)

**Comment by tmoonlight** [comment]
多谢建议，可以加一下

**Comment by tmoonlight** [comment]
1.0正式版本已经修复了你的问题
