### ISSUE TITLE
服务端建好后自动建了很多用户

### ISSUE THREAD

**Issue by peach7orange** [tmoonlight/NSmartProxy#27]
服务端刚建好，使用的docker，然后多了上百个temp_2pO5sIrqko5t 类似这样的用户？
![image](https://user-images.githubusercontent.com/14941992/63410376-c0dc2e00-c425-11e9-9887-420e0f7f1335.png)

**Comment by tmoonlight** [comment]
可能是你的服务本身就有通信故障，客户端是会在登陆异常之后会主动申请服务端账号，你可以现在配置里把匿名登陆关闭，然后自己建帐户，在客户端用自己建的帐户登陆

**Comment by tmoonlight** [comment]
1.0正式版本已经修复了你的问题
