### ISSUE TITLE
自己搭建服务器修改端口 后 无法登录

### ISSUE THREAD

**Issue by SplendidDream** [tmoonlight/NSmartProxy#28]
你好，我自己搭建服务器后修改了默认端口，并禁止了匿名登录。 在客户端登录时候 没有使用配置对话框中填写的端口号，而是使用了默认端口号 DEFAULT_WEB_PORT = 12309， 导致登录失败。这里是否有问题呢？

**Comment by tmoonlight** [comment]
把你客戶端配置和服務端配置都發出來看看

**Comment by tmoonlight** [comment]
1.0正式版本已经修复了你的问题
