### ISSUE TITLE
docker中启动后，容器会自动重启。

### ISSUE THREAD

**Issue by billsking** [tmoonlight/NSmartProxy#36]
一下是容器日志：
[root@JDu4e00u53f7 ~]# docker logs 2e3
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.2.8 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.2.8 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by tmoonlight** [comment]
多谢反馈，应该是之前升级 core没有及时更新版本引起的
