### ISSUE TITLE
X509 Certificate

### ISSUE THREAD

**Issue by Gprsk** [tmoonlight/NSmartProxy#39]
I'm trying to undestand how X509 certificates are handled and/or how they work with NSmartProxy.

Looking at the code, it was possible to find some references about loading certificates (method "InitCertificate" on class NSPServerContext.cs), but i'm having trouble undestanding how it works.

If possible, can you explain in more detail? Maybe using a few examples?

Thank you for your time!

**Comment by tmoonlight** [comment]
For example, if you want to host a website with https, you may have two methods：
1.  Host a https website on your LAN as normally，and create a tcp reverse proxy tunnel in NSmartProxy.
2.  Host a http website on your LAN without ssl certificate，create a https reverse proxy tunnel in NSmartProxy ，and attach **this certificate** to the consumerport of the website on NSmartProxy Server.
