### ISSUE TITLE
有一个bug 

### ISSUE THREAD

**Issue by yuxue521** [tmoonlight/NSmartProxy#4]
tcp client 连接服务器 程序 ，服务程序没有立即去连接 而是等到client 有数据库了才进行去连接

**Comment by tmoonlight** [comment]
> tcp client 连接服务器 程序 ，服务程序没有立即去连接 而是等到client 有数据库了才进行去连接

不是很明白。。具体怎么操作才有这种问题

**Comment by yuxue521** [comment]
电脑端建立一个 tcpserver 5900 端口  然后用你的服务端 客户端 配置好映射  例如 对外开放192.168.1.4:20000  现在使用 工具连接这个20000 的时候 没有触发 连接5900 端口 ，工具发送几个字节的数据 然后5900 端口能看到有人连接了，
2.新发现一个如果不发数据连接之后 直接断开，5900 服务端莫名的有多出来一个连接
使用 周立功 的TCP UDP测试工具 可以再现这个问题，不用自己写 tcp 服务器和客户端

**Comment by tmoonlight** [comment]
你的测试软件可否发我一份？我QQ 309052484

**Comment by yuxue521** [comment]
加了，请通过一下

**Comment by tmoonlight** [comment]
新版本已经解决了你说的问题，多谢提示！
