### ISSUE TITLE
http的Headers请求头中的参数名包含小数点“.”时后端接收不到

### ISSUE THREAD

**Issue by mwb20** [tmoonlight/NSmartProxy#40]
大佬你好！我在使用该工具作为web站点的跳板时，发现请求头中的参数名带有小数点时后端无法接收到该参数，例如：Request Headers的参数名为a.b时后端无法使用a.b获取Headers值。

我后端使用的是asp.net core 3.1开发的web api项目。

**Comment by tmoonlight** [comment]
客户端设置的连接协议是TCP还是HTTP

**Comment by mwb20** [comment]
> 客户端设置的连接协议是TCP还是HTTP

是HTTP的

**Comment by mwb20** [comment]
> 客户端设置的连接协议是TCP还是HTTP

客户端使用的是HTTP协议，没有开启压缩，配置如下：
"IsCompress": false,
"Protocol": "HTTP"

**Comment by tmoonlight** [comment]
多谢指点，应该是个bug，晚点改一下

**Comment by mwb20** [comment]
> 多谢指点，应该是个bug，晚点改一下。不过如果你没有端口重用这类需求，也可以用tcp的方式映射网站

大佬你太客气了，晚上我使用TCP试试

**Comment by mwb20** [comment]
大佬，非常抱歉！找到问题了，不是软件的问题，从使用TCP发现后端还是获取不到，最终发现是nginx配置的问题，nginx会把带有点的header视为无效的header，默认会忽略掉，配置文件中加上：ignore_invalid_headers off; 最终问题解决了。
