### ISSUE TITLE
教程有误

### ISSUE THREAD

**Issue by pluveto** [tmoonlight/NSmartProxy#43]
正确写法是：
systemctl start supervisord
service supervisord start

文中写法是：
service supervisor restart

会引发：Failed to restart supervisor.service: Unit not found.

**Comment by pluveto** [comment]
还有这里：command=/usr/nspserver_scd_linux_v1.2/NSmartProxy.ServerHost;
会引发 can't find command '/root/nat/NSmartProxy.ServerHost;'
解决方法是去掉分号。

**Comment by tmoonlight** [comment]
多谢修正！
