### ISSUE TITLE
Linux 客户端如何登录？

### ISSUE THREAD

**Issue by pluveto** [tmoonlight/NSmartProxy#45]
配置文件没有找到相关项

**Comment by tmoonlight** [comment]
dotnet NSmartProxyServer.dll -u admin -p admin
考虑到用户密码明文写在配置里不太好，所以只用在了参数里，登陆一次之后可以不带参数了

**Comment by pluveto** [comment]
我把windows gui客户端生成的cache文件复制了过去，但是并未生效？



---原始邮件---
发件人: "TMOONLIGHT"<notifications@github.com&gt;
发送时间: 2020年5月20日(周三) 下午4:54
收件人: "tmoonlight/NSmartProxy"<NSmartProxy@noreply.github.com&gt;;
抄送: "pluveto"<reg@pluvet.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [tmoonlight/NSmartProxy] Linux 客户端如何登录？ (#45)




 
dotnet NSmartProxyServer.dll -u admin -p admin
 考虑到用户密码明文写在配置里不太好，所以只用在了参数里，登陆一次之后可以不带参数了
