### ISSUE TITLE
服务端启动后，客户都安无法连接，telnent服务端无响应。

### ISSUE THREAD

**Issue by laosandegudai** [tmoonlight/NSmartProxy#5]
服务端启动后，客户都安无法连接，telnent服务端无响应。目前环境是阿里云的centos环境，端口上确定是开放的。

**Comment by tmoonlight** [comment]
有可能是你telnet的这台机器的环境禁用了端口，可以用在线测试工具测试一下

**Comment by laosandegudai** [comment]
端口确认是打开的，因为我用其它程序试过这个端口telnent测试通过

**Comment by tmoonlight** [comment]
可以发个连联系方式到我邮箱，看下你是什么问题
