### ISSUE TITLE
关于传输路径的疑问

### ISSUE THREAD

**Issue by sekkit** [tmoonlight/NSmartProxy#55]
请问从内网客户端A->外网服务器->内网客户端B，数据走的是外网服务器中转，还是直接客户端A->客户端B呢？谢谢

**Comment by duyanming** [comment]
两个内网还想直接通信?

**Comment by sekkit** [comment]
punchhole不能实现双端直连吗

**Comment by tmoonlight** [comment]
第一，目前都是走的中转。p2p功能正在测试中。

第二，题主可以先用NAT测试软件测试下两台需要通信的主机是否有一台为Full cone NAT类型，如果有，则可以启用p2p通信，否则就很难实现了。
