### ISSUE TITLE
build error:  Sequence contains no elements

### ISSUE THREAD

**Issue by Jamlee** [tmoonlight/NSmartProxy#6]
遇到构建失败的错误，看起来是  dotnet-wrap 执行失败了：

![image](https://user-images.githubusercontent.com/5196641/54182036-553b7f80-44db-11e9-955e-91d98b6c4320.png)

**Comment by tmoonlight** [comment]
dotnet-wrap是两个打包工具的集合，这个工具需要安装 core 3.0的sdk

**Comment by Jamlee** [comment]
装了 3.0 貌似还是这个问题哟。

**Comment by Jamlee** [comment]
哈哈， 使用 warp 原生工具解决了这个问题。多谢兄弟
