### ISSUE TITLE
客户端断开连接后，无法释放全部端口

### ISSUE THREAD

**Issue by wyy0709** [tmoonlight/NSmartProxy#77]
一个客户端，添加了多个端口（20001,20002），点击开始连接，再停止。这时查看仪表盘发现只有第一个端口连接会断开(20001)，第二个(20002)仍然占用连接。
补充：客户端点击停止前，正在被远程ssh连接，我不确定是否跟此事件有关。
![image](https://github.com/user-attachments/assets/caf2d0c6-62be-4061-b3bd-95470a4fd65f)

**Comment by tmoonlight** [comment]
请提供一下版本号？老版本有这个问题

**Comment by wyy0709** [comment]
> 请提供一下版本号？老版本有这个问题

服务端：
[nspserver_scd_win_v1.3_alpha.zip](https://github.com/tmoonlight/NSmartProxy/releases/download/1.3_alpha/nspserver_scd_win_v1.3_alpha.zip)
客户端：
[nspclient_winform_v1.3_alpha.zip](https://github.com/tmoonlight/NSmartProxy/releases/download/1.3_alpha/nspclient_winform_v1.3_alpha.zip)

**Comment by tmoonlight** [comment]
用1.4final版本试试，另外如果服务端属于异常断开，tcp也没有那么快关掉，属于正常现象。
如果此时重连还有问题的话那就是bug，否则可以忽略这个问题。

**Comment by wyy0709** [comment]
> 用1.4final版本试试，另外如果服务端属于异常断开，tcp也没有那么快关掉，属于正常现象。 如果此时重连还有问题的话那就是bug，否则可以忽略这个问题。

Release还没有1.4final这个版本？
不是延迟断开的原因，端口始终占用在重启服务端之前都不会释放。客户端主动断开连接时，该端口正用于ssh连接，应该是这个原因导致断开逻辑出错或者未能成功。
