### ISSUE TITLE
客户端的映射在服务器端的端口号不能指定吗？

### ISSUE THREAD

**Issue by vagile-cn** [tmoonlight/NSmartProxy#8]
客户端的映射在服务器端的端口号不能指定吗？
我看客户端配置文件 只有本地端口 没有指定服务器端口。
不知道是不是这样，望指教

**Comment by tmoonlight** [comment]
目前端口是按自动按顺序分配的，晚些时候我会加上设置端口的功能。

**Comment by tmoonlight** [comment]
功能已经加上了，你可以拿最新版本先试下

**Comment by vagile-cn** [comment]
> 功能已经加上了，你可以拿最新版本先试下。

这么速度的？
我那天试着读了读代码，感觉也有点略复杂啊~
其实感觉TCP转发这种功能应该代码量不应该太大啊
可能是有其他的考虑吧~

**Comment by tmoonlight** [comment]
> > 功能已经加上了，你可以拿最新版本先试下。
> 
> 这么速度的？
> 我那天试着读了读代码，感觉也有点略复杂啊~
> 其实感觉TCP转发这种功能应该代码量不应该太大啊
> 可能是有其他的考虑吧~

觉得哪里可以简化，可以提出来啊，共同学习

**Comment by qcjxberin** [comment]
怎么设置端口号的？

**Comment by tmoonlight** [comment]
> 怎么设置端口号的？


{

  "IP": "192.168.0.106", //反向代理机器的ip
  "TargetServicePort": "5902", //反向代理服务的端口
  **"ConsumerPort": "9878"**   //可选，消费端口，如果已被占用会自动重新分配，默认从200 },

**Comment by qcjxberin** [comment]
那是不是也可以设置为客户机的80端口的？

**Comment by tmoonlight** [comment]
> 那是不是也可以设置为80端口的？

我猜你是想解决网站显示端口的问题，如果你使用公用的服务端，80端口可能会比较抢手以致于你很难抢到这个端口。一般解决这个问题有两个方法，1.域名隐式转发(需域名提供商支持) 2.泛域名解析（需要程序支持）
