### ISSUE TITLE
tmoonlight/nspserver docker镜像报错

### ISSUE THREAD

**Issue by yhsw** [tmoonlight/NSmartProxy#80]
你好，docker pull tmoonlight/nspserver 拉取到的镜像run了报错
![QQ图片20240813201341](https://github.com/user-attachments/assets/e0373cee-7340-47ed-9e33-c435df0a6977)

**Comment by tmoonlight** [comment]
已解决，.net 8.0的裁剪机制有问题导致部分库（eg.:log4net）出现不兼容情况，回退到稳定的.net 6.0自测已经解决了问题

**Comment by yhsw** [comment]
> 已解决，.net 8.0的裁剪机制有问题导致部分库（eg.：log4net）出现不兼容情况，回退到稳定的.net 6.0自测已经解决了问题

感谢修复
