### ISSUE TITLE
新版的客户端有个地方不明白

### ISSUE THREAD

**Issue by landonzeng** [tmoonlight/NSmartProxy#82]
新版的客户端有个使用服务端配置，这是服务端后台配置客户端吗？不太明白，服务端那边要怎么配置

**Comment by landonzeng** [comment]
还有一个就是服务端里的用户绑定端口的作用是什么？

**Comment by tmoonlight** [comment]
> 新版的客户端有个使用服务端配置，这是服务端后台配置客户端吗？不太明白，服务端那边要怎么配置

后台的用户列表那里可以配置，一旦客户端勾选用户列表，后台就能把配置下发给客户端

**Comment by tmoonlight** [comment]
> 还有一个就是服务端里的用户绑定端口的作用是什么？

用户绑定端口之后，代表这个端口给这个用户独享了，其他用户无法再设置到这个端口了

**Comment by landonzeng** [comment]
> > 还有一个就是服务端里的用户绑定端口的作用是什么？
> 
> 用户绑定端口之后，代表这个端口给这个用户独享了，其他用户无法再设置到这个端口了

哦哦，明白了
